name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
      
    - name: Install NuGet client
      uses: olegtarasov/download-nuget@v1
      
    - name: Build with dotnet
      run: |
        cd src
        cd Multiverse
        dotnet build -c Release -o out
        cd ..
        cd ..
        
    - name: Add private GitHub registry to NuGet
      run: mono $NUGET_EXE sources add -name "GPR" -Source https://nuget.pkg.github.com/OpenMiNET/index.json -Username OpenMiNET -Password ${{ secrets.GITHUB_TOKEN }}
        
    - name: Push to NuGet
      run: |
        cd src
        cd Multiverse
        dotnet pack -c Release -o out /p:PackageVersion=$(date +%Y.%m.%d.%H%M%S) Multiverse.csproj
        dotnet nuget push out/*.nupkg -k ${NUGET_TOKEN} -s https://api.nuget.org/v3/index.json
        mono $NUGET_EXE push out/*.nupkg -Source "GPR"
      shell: bash
      env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
