name: .NET Core

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
      
    - name: Install NuGet client
      uses: nuget/setup-nuget@v1.0.2
      with:
        nuget-version: latest
      
    - name: Add GitHub registry to NuGet
      run: nuget sources add -name "GPR" -Source "https://nuget.pkg.github.com/OpenMiNET/index.json" -Username OpenMiNET -Password ${{ secrets.GITHUB_TOKEN }}
      
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.GITHUB_TOKEN}}
    
    - name: Build with dotnet
      run: |
        cd src
        cd Multiverse
        dotnet build -c Release -o out
        cd ..
        cd ..
        
    - name: Push to NuGet
      run: |
        cd src
        cd Multiverse
        dotnet pack -c Release -o out /p:PackageVersion=${env:BUILD_NUMBER} Multiverse.csproj
        dotnet nuget push out/*.nupkg -k ${env:NUGET_TOKEN} -s https://api.nuget.org/v3/index.json
        nuget push out/*.nupkg -Source "GPR"
      env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
